### ISSUE TITLE
Can't initialize DataDrivenInputMask 2.0 (on Mac)

### ISSUE THREAD

**Issue by dd-a** [bstroebl/DataDrivenInputMask#12]
Hi, 
I just installed DataDrivenInputMask 2.0 on QGis 3.2.3 (homebrew) on Mac OS 10.13.6 and got this error when trying to initialize a layer.  Do I miss a python module and which ?   
Here's the Python error Traceback :
`Traceback (most recent call last):

              File "/Users/didier/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/DataDrivenInputMask/datadriveninputmask.py", line 204, in initializeLayer
              fieldDisable = []) # set the defaults here because somehow some of the values persist
              File "/Users/didier/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/DataDrivenInputMask/ddmanager.py", line 169, in initLayer
              db = self.__createDb(layer)
              File "/Users/didier/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/DataDrivenInputMask/ddmanager.py", line 1043, in __createDb
              password, sslmode, authcfg)
              File "/Users/didier/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/DataDrivenInputMask/ddmanager.py", line 963, in __connectDb
              database, iface = self.iface)
              File "/Users/didier/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/DataDrivenInputMask/dderror.py", line 45, in __init__
              value, level=QgsMessageBar.CRITICAL,
             AttributeError: type object 'QgsMessageBar' has no attribute 'CRITICAL'`

**Comment by dd-a** [comment]
yes I know about that brand new release (congratulations !), I was glad to see it.  I have several database connections working and I made that test in a project with layers located in a Postgis server.  I just made another test: usually my db connections use authentifications credentials stored in my keychain, so I thought this might be the source of the trouble.  I parametrized another connection with basic login storing in the connection setting and password not stored: then trying to initialize the layer DDIM prompted for the password, I filled it in and got the same error as before.  Hth.
