### ISSUE TITLE
Cannot initialise PostGIS layer in 3.4.5

### ISSUE THREAD

**Issue by CoryAlbrecht** [bstroebl/DataDrivenInputMask#24]
The following error occurs when trying to initialise a PostGIS layer in QGIS 3.4.5 on Ubuntu 18.10

```
An error has occurred while executing Python code: 

IndexError: list index out of range 
Traceback (most recent call last):
  File "/home/cory/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataDrivenInputMask/datadriveninputmask.py", line 204, in initializeLayer
    fieldDisable = []) # set the defaults here because somehow some of the values persist
  File "/home/cory/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataDrivenInputMask/ddmanager.py", line 171, in initLayer
    thisTable = self.makeDdTable(layer,  db)
  File "/home/cory/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataDrivenInputMask/ddmanager.py", line 286, in makeDdTable
    table = relation[1].replace('"', '')
IndexError: list index out of range


Python version: 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0] 
QGIS version: 3.4.5-Madeira Madeira, de0aede 

Python Path:
/usr/share/qgis/python
/home/cory/.local/share/QGIS/QGIS3/profiles/default/python
/home/cory/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/home/cory/.local/share/QGIS/QGIS3/profiles/default/python
/usr/lib/python3/dist-packages/IPython/extensions
.
/home/cory/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataDrivenInputMask
/home/cory/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/home/cory/Documents/Alternate History/Charles In Charge
```

Table schema for the layer is:

````
CREATE TABLE "Charles in Charge"."timeline-countries"
(
    geom geometry(MultiPolygon,4326),
    name text COLLATE pg_catalog."default",
    start_date date,
    end_date date,
    main_rgb character varying(8) COLLATE pg_catalog."default",
    feature_uuid uuid NOT NULL DEFAULT uuid_generate_v4(),
    country_uuid uuid NOT NULL DEFAULT uuid_generate_v4(),
    stripe_rgb character varying(8) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    border_rgb character varying(8) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    border_shade numeric DEFAULT 0.085,
    sovereign text COLLATE pg_catalog."default",
    type text COLLATE pg_catalog."default",
    info_url text[] COLLATE pg_catalog."default" DEFAULT ARRAY[]::character varying[],
    flag_url text[] COLLATE pg_catalog."default" DEFAULT ARRAY[]::character varying[],
    predecessors uuid[] DEFAULT ARRAY[]::uuid[],
    successors uuid[] DEFAULT ARRAY[]::uuid[],
    visible boolean DEFAULT true,
    alternate_name text[] COLLATE pg_catalog."default",
    full_name text[] COLLATE pg_catalog."default",
    CONSTRAINT "timeline-countries_pkey" PRIMARY KEY (feature_uuid)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;
````

**Comment by bstroebl** [comment]
You have spaces in your schema name, get rid of them and it will work.

**Comment by CoryAlbrecht** [comment]
Spaces in an identifier are perfectly valid in PostgresQL (and numerous other SQL servers, too).

**Comment by bstroebl** [comment]
agreed, they are valid though generally not recommended but I they are not supported by DataDrivenInputMask, I am afraid.

**Comment by bstroebl** [comment]
I updated the [wiki ](https://github.com/bstroebl/DataDrivenInputMask/wiki/Precautions)to show any pitfalls.
