### ISSUE TITLE
Error connecting

### ISSUE THREAD

**Issue by pcav** [bstroebl/DataDrivenInputMask#30]
initializing a layer returns:
DdError: Could not connect to PostgreSQL database: corso
and the plugin is unusable

**Comment by bstroebl** [comment]
Hi Paolo,
with which type of connection did you load your layer into QGIS in the first place?

**Comment by pcav** [comment]
SSL preferred

**Comment by pcav** [comment]
I'm available for further testing

**Comment by bstroebl** [comment]
hi Paolo,
according to https://www.postgresql.org/docs/12/libpq-connect.html (see sslmode) "prefer" is the default. In the code I check if ssl is required and set `requiressl=1` accordingly. AFAIU prefer should work out of the box. Do you have any other output in QGIS' log?

**Comment by pcav** [comment]
2020-02-10T13:22:25     CRITICAL    DdError : Could not connect to PostgreSQL database: corso
2020-02-10T13:22:25     CRITICAL    DdError : Could not connect to PostgreSQL database: corso

thanks

**Comment by bstroebl** [comment]
Could you please test if it works with ssl required

**Comment by pcav** [comment]
modified the connection param, loaded another layer, same error (not sure qgis takes into account the connection change however)

**Comment by bstroebl** [comment]
QGIS should take it into account after restarting it
Are you using user/password or configuration?
Is this a local or remote server?

**Comment by pcav** [comment]
I confirm: sslmode=require

**Comment by pcav** [comment]
user/pwd
remote
thanks

**Comment by bstroebl** [comment]
So you use user/pwd + sslmode = require to access a remote server and get the same error?
This is exactly what I do here (QGIS 3.4.15 on Win10 or 3.4.10 on Ubuntu). 
Which version are you using?

**Comment by pcav** [comment]
Postgresql 11.5
Thanks

**Comment by bstroebl** [comment]
I meant QGIS - Version :-)

**Comment by pcav** [comment]
3.4.15

**Comment by bstroebl** [comment]
Paolo,
I really do not have a clue how to proceed here. I have 100+ users in my institution using the plugin (admittedly with the same set up that I have) with no errors. I added a line in the code to show more information and pushed to the develop branch a890aab92750c30a26fa0e12273efbc29c41bcba
Please replace ddManager.py in your installation with the one from the develop branch.

**Comment by pcav** [comment]
A more meaningful message:
`2020-02-14T16:26:14     WARNING    Traceback (most recent call last):
              File "/home/paolo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataDrivenInputMask/ddmanager.py", line 1089, in __createDb
              user = layerSrc["user"]
             KeyError: 'user'
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "/home/paolo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataDrivenInputMask/datadriveninputmask.py", line 204, in initializeLayer
              fieldDisable = []) # set the defaults here because somehow some of the values persist
              File "/home/paolo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataDrivenInputMask/ddmanager.py", line 171, in initLayer
              db = self.__createDb(layer)
              File "/home/paolo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataDrivenInputMask/ddmanager.py", line 1094, in __createDb
              dbname + "." + host)
             UnboundLocalError: local variable 'dbname' referenced before assignment`

**Comment by bstroebl** [comment]
Hi Paolo,
any news in this question from your side? Could you please use the newest files from develop branch and try with them?

**Comment by pcav** [comment]
Trying now.

**Comment by pcav** [comment]
Now a different error:
```
2020-05-18T16:28:15     WARNING    Traceback (most recent call last):
              File "/home/paolo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataDrivenInputMask-master/datadriveninputmask.py", line 200, in initializeLayer
              self.app.ddManager.initLayer(layer, skip = [], labels = {},
              File "/home/paolo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataDrivenInputMask-master/ddmanager.py", line 171, in initLayer
              db = self.__createDb(layer)
              File "/home/paolo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataDrivenInputMask-master/ddmanager.py", line 1128, in __createDb
              db = self.__connectDb(layer.id(), host, dbname,
              File "/home/paolo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataDrivenInputMask-master/ddmanager.py", line 1050, in __connectDb
              self.showError(db.lastError())
              File "/home/paolo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataDrivenInputMask-master/ddmanager.py", line 1520, in showError
              DdError(msg, iface = self.iface)
              File "/home/paolo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataDrivenInputMask-master/dderror.py", line 44, in __init__
              iface.messageBar().pushMessage("DdError",
             TypeError: QgsMessageBar.pushMessage(): arguments did not match any overloaded call:
              overload 1: argument 2 has unexpected type 'QSqlError'
              overload 2: argument 2 has unexpected type 'QSqlError'
              overload 3: argument 2 has unexpected type 'QSqlError'
             
```
Cheers.

**Comment by bstroebl** [comment]
too bad, sorry. I (tried to) fix it in develop branch (ddmanager.py)

**Comment by pcav** [comment]
I'm available for further testing. Just let me know.
Cheers.
