### ISSUE TITLE
Initialize layer

### ISSUE THREAD

**Issue by kamparli** [bstroebl/DataDrivenInputMask#31]
Can not initialize a point layer 
 Traceback (most recent call last):
              File "C:/Users/HP/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataDrivenInputMask\datadriveninputmask.py", line 204, in initializeLayer
              fieldDisable = []) # set the defaults here because somehow some of the values persist
              File "C:/Users/HP/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataDrivenInputMask\ddmanager.py", line 173, in initLayer
              thisTable = self.makeDdTable(layer, db)
              File "C:/Users/HP/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataDrivenInputMask\ddmanager.py", line 290, in makeDdTable
              table = relation[1].replace('"', '')
             IndexError: list index out of range

BRGDS
Karl

**Comment by bstroebl** [comment]
Please see https://github.com/bstroebl/DataDrivenInputMask/wiki/Precautions and double check if you followed this advice.

**Comment by bstroebl** [comment]
Please close this issue, if it has been solved.
