### ISSUE TITLE
No module named 'DataDrivenInputMask.datadriveninputmask'

### ISSUE THREAD

**Issue by AKouz1649** [bstroebl/DataDrivenInputMask#36]
Trying to install the plugin on QGIS 3.10.14 on Linux and receive the following error.

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/**********/.local/share/QGIS/QGIS3/profiles/************/python/plugins/DataDrivenInputMask/__init__.py", line 28, in classFactory
    from .datadriveninputmask import DataDrivenInputMask
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'DataDrivenInputMask.datadriveninputmask'

```

Python version: 3.9.7 (default, Jun 22 2022, 20:11:26) [GCC 11.2.0] 
QGIS version: 3.10.14-A Coruña A Coruña, exported

**Comment by bstroebl** [comment]
Hi can you sucessfully install any other Python plugins?
Although I doubt this has anything to do with your problem: Why are you running such an old version of QGIS?

**Comment by bstroebl** [comment]
Are you using the Python envirnomnent of the system or the one that QGIS did install? Probably is a missmatch between QGIS and Python Versions. I am running QGIS3.22 which brings Python 3.9.5 (this is on Win10, though).
