### ISSUE TITLE
Uncaught UnicodeEncodeError: 'ascii' codec can't encode character u'\xdf' in position 4: ordinal not in range(128)


### ISSUE THREAD

**Issue by peter-shr** [bstroebl/DataDrivenInputMask#9]
Steps to reproduce
 1. First - The query works in other project files.
 I don't know if it's just this layer/database source?
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/Users/USER/.qgis2/python/plugins\DataDrivenInputMask\datadriveninputmask.py", line 201, in initializeLayer
    fieldDisable = []) # set the defaults here because somehow some of the values persist
  File "C:/Users/USER/.qgis2/python/plugins\DataDrivenInputMask\ddmanager.py", line 192, in initLayer
    readConfigTables = readConfigTables, fieldDisable = fieldDisable)
  File "C:/Users/USER/.qgis2/python/plugins\DataDrivenInputMask\ddui.py", line 414, in createUi
    readConfigTables, createAction, fieldDisable)
  File "C:/Users/USER/.qgis2/python/plugins\DataDrivenInputMask\ddui.py", line 210, in __createForms
    thisTable, db, labels, minMax, fieldDisable = fieldDisable)
  File "C:/Users/USER/.qgis2/python/plugins\DataDrivenInputMask\ddui.py", line 819, in getAttributes
    attLabel = labels[str(attName)]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xdf' in position 4: ordinal not in range(128)

```
DataDrivenInputMask 1.3.1, QGIS 2.14.22-Essen on Windows 10

**Comment by bstroebl** [comment]
As a general rule you should only use ascii characters in field names (and relation names, too). The error is thrown because a non-ascii character is encountered in a field name. So check your table's fields for non ascii characters and rename them.
Nevertheless the error should be caught, will be fixed for QGIS 3.

**Comment by bstroebl** [comment]
error is caught now
